/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hassan.askar.easymcu;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author askar
 */
public class CurrentProject extends javax.swing.JFrame {

    private static String currentFile, name;

    DynamicView DV = new DynamicView();

    DynamicView DVPA0 = new DynamicView();
    DynamicView DVPA1 = new DynamicView();
    DynamicView DVPA2 = new DynamicView();
    DynamicView DVPA3 = new DynamicView();
    DynamicView DVPA4 = new DynamicView();
    DynamicView DVPA5 = new DynamicView();
    DynamicView DVPA6 = new DynamicView();
    DynamicView DVPA7 = new DynamicView();

    DynamicView DVPB0 = new DynamicView();
    DynamicView DVPB1 = new DynamicView();
    DynamicView DVPB2 = new DynamicView();
    DynamicView DVPB3 = new DynamicView();
    DynamicView DVPB4 = new DynamicView();
    DynamicView DVPB5 = new DynamicView();
    DynamicView DVPB6 = new DynamicView();
    DynamicView DVPB7 = new DynamicView();

    DynamicView DVPC0 = new DynamicView();
    DynamicView DVPC1 = new DynamicView();
    DynamicView DVPC2 = new DynamicView();
    DynamicView DVPC3 = new DynamicView();
    DynamicView DVPC4 = new DynamicView();
    DynamicView DVPC5 = new DynamicView();
    DynamicView DVPC6 = new DynamicView();
    DynamicView DVPC7 = new DynamicView();

    DynamicView DVPD0 = new DynamicView();
    DynamicView DVPD1 = new DynamicView();
    DynamicView DVPD2 = new DynamicView();
    DynamicView DVPD3 = new DynamicView();
    DynamicView DVPD4 = new DynamicView();
    DynamicView DVPD5 = new DynamicView();
    DynamicView DVPD6 = new DynamicView();
    DynamicView DVPD7 = new DynamicView();

    Color panelMovingColor = new Color(41, 57, 80);
    Color labelMovingColor = new Color(255, 128, 0);
    private String config[] = {PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_INPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString(), PIN_DIR.DIO_u8_OUTPUT.toString()};

    /**
     * Creates new form CurrentProject
     */
    public CurrentProject(String Location, String Name) {
        initComponents();
        name = Name;
        this.setTitle(name);
        currentFile = Location;
        projectNameLabel.setText(name);
        getPinsDirection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalPanel = new javax.swing.JPanel();
        DIOContentPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        AVRIcon = new javax.swing.JLabel();
        PB0_Label = new javax.swing.JLabel();
        PB2_Label = new javax.swing.JLabel();
        PA0_Label = new javax.swing.JLabel();
        PA1_Label = new javax.swing.JLabel();
        PA2_Label = new javax.swing.JLabel();
        PA3_Label = new javax.swing.JLabel();
        PA4_Label = new javax.swing.JLabel();
        PA5_Label = new javax.swing.JLabel();
        PA6_Label = new javax.swing.JLabel();
        PA7_Label = new javax.swing.JLabel();
        PC7_Label = new javax.swing.JLabel();
        PC6_Label = new javax.swing.JLabel();
        PC5_Label = new javax.swing.JLabel();
        PC4_Label = new javax.swing.JLabel();
        PC3_Label = new javax.swing.JLabel();
        PC2_Label = new javax.swing.JLabel();
        PC1_Label = new javax.swing.JLabel();
        PC0_Label = new javax.swing.JLabel();
        PD0_Label = new javax.swing.JLabel();
        PD1_Label = new javax.swing.JLabel();
        PD2_Label = new javax.swing.JLabel();
        PD3_Label = new javax.swing.JLabel();
        PD4_Label = new javax.swing.JLabel();
        PD5_Label = new javax.swing.JLabel();
        PD6_Label = new javax.swing.JLabel();
        PD7_Label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ApplyPanel = new javax.swing.JPanel();
        pointerApplyPanel = new javax.swing.JPanel();
        ApplyLabel = new javax.swing.JLabel();
        ApplyIconLabel = new javax.swing.JLabel();
        PB1_Label = new javax.swing.JLabel();
        PB3_Label = new javax.swing.JLabel();
        PB4_Label = new javax.swing.JLabel();
        PB5_Label = new javax.swing.JLabel();
        PB6_Label = new javax.swing.JLabel();
        PB7_Label5 = new javax.swing.JLabel();
        USARTContentPanel = new javax.swing.JPanel();
        exitLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ADCContentPanel = new javax.swing.JPanel();
        exitLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        projectNamePanel = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DIOPanel = new javax.swing.JPanel();
        pointerDIOPanel = new javax.swing.JPanel();
        DIOLabel = new javax.swing.JLabel();
        DIOIconLabel = new javax.swing.JLabel();
        ADCPanel = new javax.swing.JPanel();
        pointerADCPanel = new javax.swing.JPanel();
        ADCLabel = new javax.swing.JLabel();
        ADCIconLabel = new javax.swing.JLabel();
        USARTPanel = new javax.swing.JPanel();
        pointerUSARTPanel = new javax.swing.JPanel();
        USARTLabel = new javax.swing.JLabel();
        USARTIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(82, 133, 212));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        generalPanel.setBackground(new java.awt.Color(82, 133, 212));
        generalPanel.setLayout(new java.awt.CardLayout());

        DIOContentPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabelMouseMoved(evt);
            }
        });
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        AVRIcon.setIcon(new javax.swing.ImageIcon("/home/askar/NetBeansProjects/EasyMCU/Images/ATmega32_DIO.png")); // NOI18N

        PB0_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB0_Label.setForeground(Color.white);
        PB0_Label.setText("PB0 OUTPUT");
        PB0_Label.setName("PB0"); // NOI18N
        PB0_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB0_LabelMouseMoved(evt);
            }
        });
        PB0_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB0_LabelMouseExited(evt);
            }
        });

        PB2_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB2_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB2_Label.setText("PB2");
        PB2_Label.setName("PB2"); // NOI18N
        PB2_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB2_LabelMouseMoved(evt);
            }
        });
        PB2_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB2_LabelMouseExited(evt);
            }
        });

        PA0_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA0_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA0_Label.setText("PA0 OUTPUT");
        PA0_Label.setName("PA0"); // NOI18N
        PA0_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA0_LabelMouseMoved(evt);
            }
        });
        PA0_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PA0_LabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA0_LabelMouseExited(evt);
            }
        });

        PA1_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA1_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA1_Label.setText("PA1");
        PA1_Label.setName("PA1"); // NOI18N
        PA1_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA1_LabelMouseMoved(evt);
            }
        });
        PA1_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PA1_LabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA1_LabelMouseExited(evt);
            }
        });

        PA2_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA2_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA2_Label.setText("PA2");
        PA2_Label.setName("PA2"); // NOI18N
        PA2_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA2_LabelMouseMoved(evt);
            }
        });
        PA2_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PA2_LabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA2_LabelMouseExited(evt);
            }
        });

        PA3_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA3_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA3_Label.setText("PA3");
        PA3_Label.setName("PA3"); // NOI18N
        PA3_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA3_LabelMouseMoved(evt);
            }
        });
        PA3_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA3_LabelMouseExited(evt);
            }
        });

        PA4_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA4_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA4_Label.setText("PA4");
        PA4_Label.setName("PA4"); // NOI18N
        PA4_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA4_LabelMouseMoved(evt);
            }
        });
        PA4_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA4_LabelMouseExited(evt);
            }
        });

        PA5_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA5_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA5_Label.setText("PA5");
        PA5_Label.setName("PA5"); // NOI18N
        PA5_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA5_LabelMouseMoved(evt);
            }
        });
        PA5_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA5_LabelMouseExited(evt);
            }
        });

        PA6_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA6_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA6_Label.setText("PA6");
        PA6_Label.setName("PA6"); // NOI18N
        PA6_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA6_LabelMouseMoved(evt);
            }
        });
        PA6_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA6_LabelMouseExited(evt);
            }
        });

        PA7_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PA7_Label.setForeground(new java.awt.Color(254, 254, 254));
        PA7_Label.setText("PA7");
        PA7_Label.setName("PA7"); // NOI18N
        PA7_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PA7_LabelMouseMoved(evt);
            }
        });
        PA7_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PA7_LabelMouseExited(evt);
            }
        });

        PC7_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC7_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC7_Label.setText("PC7");
        PC7_Label.setName("PC7"); // NOI18N
        PC7_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC7_LabelMouseMoved(evt);
            }
        });
        PC7_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC7_LabelMouseExited(evt);
            }
        });

        PC6_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC6_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC6_Label.setText("PC6");
        PC6_Label.setName("PC6"); // NOI18N
        PC6_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC6_LabelMouseMoved(evt);
            }
        });
        PC6_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC6_LabelMouseExited(evt);
            }
        });

        PC5_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC5_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC5_Label.setText("PC5");
        PC5_Label.setName("PC5"); // NOI18N
        PC5_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC5_LabelMouseMoved(evt);
            }
        });
        PC5_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC5_LabelMouseExited(evt);
            }
        });

        PC4_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC4_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC4_Label.setText("PC4");
        PC4_Label.setName("PC4"); // NOI18N
        PC4_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC4_LabelMouseMoved(evt);
            }
        });
        PC4_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC4_LabelMouseExited(evt);
            }
        });

        PC3_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC3_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC3_Label.setText("PC3");
        PC3_Label.setName("PC3"); // NOI18N
        PC3_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC3_LabelMouseMoved(evt);
            }
        });
        PC3_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC3_LabelMouseExited(evt);
            }
        });

        PC2_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC2_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC2_Label.setText("PC2");
        PC2_Label.setName("PC2"); // NOI18N
        PC2_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC2_LabelMouseMoved(evt);
            }
        });
        PC2_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC2_LabelMouseExited(evt);
            }
        });

        PC1_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC1_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC1_Label.setText("PC1");
        PC1_Label.setName("PC1"); // NOI18N
        PC1_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC1_LabelMouseMoved(evt);
            }
        });
        PC1_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC1_LabelMouseExited(evt);
            }
        });

        PC0_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PC0_Label.setForeground(new java.awt.Color(254, 254, 254));
        PC0_Label.setText("PC0");
        PC0_Label.setName("PC0"); // NOI18N
        PC0_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PC0_LabelMouseMoved(evt);
            }
        });
        PC0_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PC0_LabelMouseExited(evt);
            }
        });

        PD0_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD0_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD0_Label.setText("PD0");
        PD0_Label.setName("PD0"); // NOI18N
        PD0_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD0_LabelMouseMoved(evt);
            }
        });
        PD0_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD0_LabelMouseExited(evt);
            }
        });

        PD1_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD1_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD1_Label.setText("PD1");
        PD1_Label.setName("PD1"); // NOI18N
        PD1_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD1_LabelMouseMoved(evt);
            }
        });
        PD1_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD1_LabelMouseExited(evt);
            }
        });

        PD2_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD2_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD2_Label.setText("PD2");
        PD2_Label.setName("PD2"); // NOI18N
        PD2_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD2_LabelMouseMoved(evt);
            }
        });
        PD2_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD2_LabelMouseExited(evt);
            }
        });

        PD3_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD3_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD3_Label.setText("PD3");
        PD3_Label.setName("PD3"); // NOI18N
        PD3_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD3_LabelMouseMoved(evt);
            }
        });
        PD3_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD3_LabelMouseExited(evt);
            }
        });

        PD4_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD4_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD4_Label.setText("PD4");
        PD4_Label.setName("PD4"); // NOI18N
        PD4_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD4_LabelMouseMoved(evt);
            }
        });
        PD4_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD4_LabelMouseExited(evt);
            }
        });

        PD5_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD5_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD5_Label.setText("PD5");
        PD5_Label.setName("PD5"); // NOI18N
        PD5_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD5_LabelMouseMoved(evt);
            }
        });
        PD5_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD5_LabelMouseExited(evt);
            }
        });

        PD6_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD6_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD6_Label.setText("PD6");
        PD6_Label.setName("PD6"); // NOI18N
        PD6_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD6_LabelMouseMoved(evt);
            }
        });
        PD6_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD6_LabelMouseExited(evt);
            }
        });

        PD7_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PD7_Label.setForeground(new java.awt.Color(254, 254, 254));
        PD7_Label.setText("PD7");
        PD7_Label.setName("PD7"); // NOI18N
        PD7_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PD7_LabelMouseMoved(evt);
            }
        });
        PD7_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PD7_LabelMouseExited(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 128, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Instructions");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 128, 0));
        jLabel4.setText("To Toggle The Pin  Direction, Click On It.");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 128, 0));
        jLabel5.setText("If Pin Color is WHITE , The Pin Direction is Input");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 128, 0));
        jLabel6.setText("If Pin Color is BLACK , The Pin Direction is Output");

        ApplyPanel.setBackground(new java.awt.Color(35, 64, 102));
        ApplyPanel.setForeground(new java.awt.Color(35, 64, 102));
        ApplyPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ApplyPanelMouseMoved(evt);
            }
        });
        ApplyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplyPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ApplyPanelMouseExited(evt);
            }
        });

        pointerApplyPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerApplyPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerApplyPanel.setOpaque(false);

        javax.swing.GroupLayout pointerApplyPanelLayout = new javax.swing.GroupLayout(pointerApplyPanel);
        pointerApplyPanel.setLayout(pointerApplyPanelLayout);
        pointerApplyPanelLayout.setHorizontalGroup(
            pointerApplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerApplyPanelLayout.setVerticalGroup(
            pointerApplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ApplyLabel.setBackground(new java.awt.Color(35, 64, 102));
        ApplyLabel.setForeground(new java.awt.Color(255, 255, 255));
        ApplyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ApplyLabel.setText("Apply On Driver");

        javax.swing.GroupLayout ApplyPanelLayout = new javax.swing.GroupLayout(ApplyPanel);
        ApplyPanel.setLayout(ApplyPanelLayout);
        ApplyPanelLayout.setHorizontalGroup(
            ApplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplyPanelLayout.createSequentialGroup()
                .addComponent(pointerApplyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApplyIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        ApplyPanelLayout.setVerticalGroup(
            ApplyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerApplyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ApplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(ApplyIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PB1_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB1_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB1_Label.setText("PB1");
        PB1_Label.setName("PB0"); // NOI18N
        PB1_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB1_LabelMouseMoved(evt);
            }
        });
        PB1_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB1_LabelMouseExited(evt);
            }
        });

        PB3_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB3_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB3_Label.setText("PB2");
        PB3_Label.setName("PB2"); // NOI18N
        PB3_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB3_LabelMouseMoved(evt);
            }
        });
        PB3_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB3_LabelMouseExited(evt);
            }
        });

        PB4_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB4_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB4_Label.setText("PB2");
        PB4_Label.setName("PB2"); // NOI18N
        PB4_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB4_LabelMouseMoved(evt);
            }
        });
        PB4_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB4_LabelMouseExited(evt);
            }
        });

        PB5_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB5_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB5_Label.setText("PB2");
        PB5_Label.setName("PB2"); // NOI18N
        PB5_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB5_LabelMouseMoved(evt);
            }
        });
        PB5_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB5_LabelMouseExited(evt);
            }
        });

        PB6_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB6_Label.setForeground(new java.awt.Color(254, 254, 254));
        PB6_Label.setText("PB2");
        PB6_Label.setName("PB2"); // NOI18N
        PB6_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB6_LabelMouseMoved(evt);
            }
        });
        PB6_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB6_LabelMouseExited(evt);
            }
        });

        PB7_Label5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PB7_Label5.setForeground(new java.awt.Color(254, 254, 254));
        PB7_Label5.setText("PB2");
        PB7_Label5.setName("PB2"); // NOI18N
        PB7_Label5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PB7_Label5MouseMoved(evt);
            }
        });
        PB7_Label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB7_Label5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout DIOContentPanelLayout = new javax.swing.GroupLayout(DIOContentPanel);
        DIOContentPanel.setLayout(DIOContentPanelLayout);
        DIOContentPanelLayout.setHorizontalGroup(
            DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(DIOContentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DIOContentPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PB0_Label)
                    .addComponent(PB2_Label)
                    .addComponent(PD0_Label)
                    .addComponent(PD1_Label)
                    .addComponent(PD2_Label)
                    .addComponent(PD3_Label)
                    .addComponent(PD4_Label)
                    .addComponent(PD5_Label)
                    .addComponent(PD6_Label)
                    .addComponent(PB1_Label)
                    .addComponent(PB3_Label)
                    .addComponent(PB4_Label)
                    .addComponent(PB5_Label)
                    .addComponent(PB6_Label)
                    .addComponent(PB7_Label5))
                .addGap(18, 18, 18)
                .addComponent(AVRIcon)
                .addGap(18, 18, 18)
                .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PD7_Label)
                    .addComponent(PC0_Label)
                    .addComponent(PC1_Label)
                    .addComponent(PC2_Label)
                    .addComponent(PC3_Label)
                    .addComponent(PC4_Label)
                    .addComponent(PC5_Label)
                    .addComponent(PC6_Label)
                    .addComponent(PC7_Label)
                    .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PA0_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA1_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA2_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA3_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA5_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA6_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA7_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PA4_Label, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DIOContentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DIOContentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ApplyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DIOContentPanelLayout.setVerticalGroup(
            DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DIOContentPanelLayout.createSequentialGroup()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DIOContentPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(PB0_Label)
                        .addGap(12, 12, 12)
                        .addComponent(PB1_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PB2_Label)
                        .addGap(18, 18, 18)
                        .addComponent(PB3_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PB4_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PB5_Label)
                        .addGap(18, 18, 18)
                        .addComponent(PB6_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PB7_Label5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PD0_Label)
                        .addGap(18, 18, 18)
                        .addComponent(PD1_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PD2_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PD3_Label)
                        .addGap(16, 16, 16)
                        .addComponent(PD4_Label)
                        .addGap(18, 18, 18)
                        .addComponent(PD5_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PD6_Label)
                        .addGap(43, 43, 43))
                    .addGroup(DIOContentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AVRIcon)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DIOContentPanelLayout.createSequentialGroup()
                        .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DIOContentPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(DIOContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DIOContentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ApplyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DIOContentPanelLayout.createSequentialGroup()
                                        .addComponent(PA0_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PA1_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PA2_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PA3_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PA4_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PA5_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PA6_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PA7_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PC7_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PC6_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PC5_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PC4_Label)
                                        .addGap(12, 12, 12)
                                        .addComponent(PC3_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PC2_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PC1_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(PC0_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PD7_Label)
                                        .addGap(29, 29, 29))))
                            .addGroup(DIOContentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)))
                        .addContainerGap())))
        );

        generalPanel.add(DIOContentPanel, "card2");

        USARTContentPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel4.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel4.setText("X");
        exitLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabel4MouseMoved(evt);
            }
        });
        exitLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel4MouseExited(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout USARTContentPanelLayout = new javax.swing.GroupLayout(USARTContentPanel);
        USARTContentPanel.setLayout(USARTContentPanelLayout);
        USARTContentPanelLayout.setHorizontalGroup(
            USARTContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, USARTContentPanelLayout.createSequentialGroup()
                .addGap(0, 965, Short.MAX_VALUE)
                .addComponent(exitLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, USARTContentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(365, 365, 365))
        );
        USARTContentPanelLayout.setVerticalGroup(
            USARTContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USARTContentPanelLayout.createSequentialGroup()
                .addComponent(exitLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        generalPanel.add(USARTContentPanel, "card2");

        ADCContentPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel3.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel3.setText("X");
        exitLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabel3MouseMoved(evt);
            }
        });
        exitLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel3MouseExited(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout ADCContentPanelLayout = new javax.swing.GroupLayout(ADCContentPanel);
        ADCContentPanel.setLayout(ADCContentPanelLayout);
        ADCContentPanelLayout.setHorizontalGroup(
            ADCContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ADCContentPanelLayout.createSequentialGroup()
                .addGap(0, 965, Short.MAX_VALUE)
                .addComponent(exitLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ADCContentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
        );
        ADCContentPanelLayout.setVerticalGroup(
            ADCContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADCContentPanelLayout.createSequentialGroup()
                .addComponent(exitLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(513, Short.MAX_VALUE))
        );

        generalPanel.add(ADCContentPanel, "card2");

        sidePanel.setBackground(new java.awt.Color(35, 64, 102));
        sidePanel.setForeground(new java.awt.Color(35, 64, 102));

        projectNamePanel.setBackground(new java.awt.Color(35, 64, 102));
        projectNamePanel.setForeground(new java.awt.Color(35, 64, 102));

        projectNameLabel.setBackground(new java.awt.Color(35, 64, 102));
        projectNameLabel.setFont(new java.awt.Font("URW Bookman", 1, 24)); // NOI18N
        projectNameLabel.setForeground(new java.awt.Color(254, 254, 254));
        projectNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout projectNamePanelLayout = new javax.swing.GroupLayout(projectNamePanel);
        projectNamePanel.setLayout(projectNamePanelLayout);
        projectNamePanelLayout.setHorizontalGroup(
            projectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        projectNamePanelLayout.setVerticalGroup(
            projectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DIOPanel.setBackground(new java.awt.Color(35, 64, 102));
        DIOPanel.setForeground(new java.awt.Color(35, 64, 102));
        DIOPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DIOPanelMouseMoved(evt);
            }
        });
        DIOPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DIOPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DIOPanelMouseExited(evt);
            }
        });

        pointerDIOPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerDIOPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerDIOPanel.setOpaque(false);

        javax.swing.GroupLayout pointerDIOPanelLayout = new javax.swing.GroupLayout(pointerDIOPanel);
        pointerDIOPanel.setLayout(pointerDIOPanelLayout);
        pointerDIOPanelLayout.setHorizontalGroup(
            pointerDIOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerDIOPanelLayout.setVerticalGroup(
            pointerDIOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        DIOLabel.setBackground(new java.awt.Color(35, 64, 102));
        DIOLabel.setForeground(new java.awt.Color(255, 255, 255));
        DIOLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DIOLabel.setText("DIO");
        DIOLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DIOIconLabel.setBackground(new java.awt.Color(35, 64, 102));
        DIOIconLabel.setForeground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout DIOPanelLayout = new javax.swing.GroupLayout(DIOPanel);
        DIOPanel.setLayout(DIOPanelLayout);
        DIOPanelLayout.setHorizontalGroup(
            DIOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DIOPanelLayout.createSequentialGroup()
                .addComponent(pointerDIOPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(DIOIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DIOLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DIOPanelLayout.setVerticalGroup(
            DIOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerDIOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DIOPanelLayout.createSequentialGroup()
                .addComponent(DIOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(DIOIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ADCPanel.setBackground(new java.awt.Color(35, 64, 102));
        ADCPanel.setForeground(new java.awt.Color(35, 64, 102));
        ADCPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ADCPanelMouseMoved(evt);
            }
        });
        ADCPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADCPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADCPanelMouseExited(evt);
            }
        });

        pointerADCPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerADCPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerADCPanel.setOpaque(false);

        javax.swing.GroupLayout pointerADCPanelLayout = new javax.swing.GroupLayout(pointerADCPanel);
        pointerADCPanel.setLayout(pointerADCPanelLayout);
        pointerADCPanelLayout.setHorizontalGroup(
            pointerADCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerADCPanelLayout.setVerticalGroup(
            pointerADCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ADCLabel.setBackground(new java.awt.Color(35, 64, 102));
        ADCLabel.setForeground(new java.awt.Color(255, 255, 255));
        ADCLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ADCLabel.setText("ADC");
        ADCLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ADCIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout ADCPanelLayout = new javax.swing.GroupLayout(ADCPanel);
        ADCPanel.setLayout(ADCPanelLayout);
        ADCPanelLayout.setHorizontalGroup(
            ADCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADCPanelLayout.createSequentialGroup()
                .addComponent(pointerADCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(ADCIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADCLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ADCPanelLayout.setVerticalGroup(
            ADCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerADCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ADCPanelLayout.createSequentialGroup()
                .addComponent(ADCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ADCIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        USARTPanel.setBackground(new java.awt.Color(35, 64, 102));
        USARTPanel.setForeground(new java.awt.Color(35, 64, 102));
        USARTPanel.setToolTipText("");
        USARTPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                USARTPanelMouseMoved(evt);
            }
        });
        USARTPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USARTPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                USARTPanelMouseExited(evt);
            }
        });

        pointerUSARTPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerUSARTPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerUSARTPanel.setOpaque(false);

        javax.swing.GroupLayout pointerUSARTPanelLayout = new javax.swing.GroupLayout(pointerUSARTPanel);
        pointerUSARTPanel.setLayout(pointerUSARTPanelLayout);
        pointerUSARTPanelLayout.setHorizontalGroup(
            pointerUSARTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerUSARTPanelLayout.setVerticalGroup(
            pointerUSARTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        USARTLabel.setBackground(new java.awt.Color(35, 64, 102));
        USARTLabel.setForeground(new java.awt.Color(255, 255, 255));
        USARTLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        USARTLabel.setText("USART");
        USARTLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        USARTIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout USARTPanelLayout = new javax.swing.GroupLayout(USARTPanel);
        USARTPanel.setLayout(USARTPanelLayout);
        USARTPanelLayout.setHorizontalGroup(
            USARTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USARTPanelLayout.createSequentialGroup()
                .addComponent(pointerUSARTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(USARTIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(USARTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        USARTPanelLayout.setVerticalGroup(
            USARTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerUSARTPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(USARTPanelLayout.createSequentialGroup()
                .addComponent(USARTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(USARTIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DIOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ADCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(USARTPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(projectNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(projectNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DIOPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ADCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(USARTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DIOPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIOPanelMouseMoved
        DV.movingMouseStyle(DIOPanel, pointerDIOPanel, DIOLabel, panelMovingColor, labelMovingColor);
    }//GEN-LAST:event_DIOPanelMouseMoved

    private void DIOPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIOPanelMouseClicked
        DV.switchPanelTo(generalPanel, DIOContentPanel);
    }//GEN-LAST:event_DIOPanelMouseClicked

    private void DIOPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIOPanelMouseExited
        DV.exiteMouseStyle(DIOPanel, pointerDIOPanel, DIOLabel);
    }//GEN-LAST:event_DIOPanelMouseExited

    private void ADCPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADCPanelMouseMoved
        DV.movingMouseStyle(ADCPanel, pointerADCPanel, ADCLabel, panelMovingColor, labelMovingColor);
    }//GEN-LAST:event_ADCPanelMouseMoved

    private void ADCPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADCPanelMouseClicked
        DV.switchPanelTo(generalPanel, ADCContentPanel);
    }//GEN-LAST:event_ADCPanelMouseClicked

    private void ADCPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADCPanelMouseExited
        DV.exiteMouseStyle(ADCPanel, pointerADCPanel, ADCLabel);
    }//GEN-LAST:event_ADCPanelMouseExited

    private void USARTPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USARTPanelMouseMoved
        DV.movingMouseStyle(USARTPanel, pointerUSARTPanel, USARTLabel, panelMovingColor, labelMovingColor);
    }//GEN-LAST:event_USARTPanelMouseMoved

    private void USARTPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USARTPanelMouseClicked
        DV.switchPanelTo(generalPanel, USARTContentPanel);
    }//GEN-LAST:event_USARTPanelMouseClicked

    private void USARTPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USARTPanelMouseExited
        DV.exiteMouseStyle(USARTPanel, pointerUSARTPanel, USARTLabel);
    }//GEN-LAST:event_USARTPanelMouseExited

    private void exitLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel3MouseMoved

    private void exitLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel3MouseClicked

    private void exitLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel3MouseExited

    private void exitLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel4MouseMoved

    private void exitLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel4MouseClicked

    private void exitLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel4MouseExited
    int xx, xy;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void ApplyPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyPanelMouseExited
        DV.exiteMouseStyle(ApplyPanel, pointerApplyPanel, ApplyLabel);
    }//GEN-LAST:event_ApplyPanelMouseExited

    private void ApplyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyPanelMouseClicked

    }//GEN-LAST:event_ApplyPanelMouseClicked

    private void ApplyPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyPanelMouseMoved
        DV.movingMouseStyle(ApplyPanel, pointerApplyPanel, ApplyLabel, panelMovingColor, labelMovingColor);
    }//GEN-LAST:event_ApplyPanelMouseMoved

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setForeground(Color.black);
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseMoved
        exitLabel.setForeground(Color.red);
    }//GEN-LAST:event_exitLabelMouseMoved

    private void PB0_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB0_LabelMouseMoved

        DVPB0.movingMouseStyle(PB0_Label, labelMovingColor);
    }//GEN-LAST:event_PB0_LabelMouseMoved

    private void PB0_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB0_LabelMouseExited
        DVPB0.exiteMouseStyle(PB0_Label);

    }//GEN-LAST:event_PB0_LabelMouseExited

    private void PB1_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB1_LabelMouseMoved
        DVPB1.movingMouseStyle(PB1_Label, labelMovingColor);
    }//GEN-LAST:event_PB1_LabelMouseMoved

    private void PB1_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB1_LabelMouseExited
        DVPB1.exiteMouseStyle(PB1_Label);
    }//GEN-LAST:event_PB1_LabelMouseExited

    private void PB2_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB2_LabelMouseExited
        DVPB2.exiteMouseStyle(PB2_Label);

    }//GEN-LAST:event_PB2_LabelMouseExited

    private void PB2_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB2_LabelMouseMoved
        DVPB2.movingMouseStyle(PB2_Label, labelMovingColor);
    }//GEN-LAST:event_PB2_LabelMouseMoved

    private void PB3_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB3_LabelMouseMoved
        DVPB3.movingMouseStyle(PB3_Label, labelMovingColor);
    }//GEN-LAST:event_PB3_LabelMouseMoved

    private void PB3_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB3_LabelMouseExited
        DVPB3.exiteMouseStyle(PB3_Label);
    }//GEN-LAST:event_PB3_LabelMouseExited

    private void PB4_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB4_LabelMouseMoved
        DVPB4.movingMouseStyle(PB4_Label, labelMovingColor);
    }//GEN-LAST:event_PB4_LabelMouseMoved

    private void PB4_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB4_LabelMouseExited
        DVPB4.exiteMouseStyle(PB4_Label);
    }//GEN-LAST:event_PB4_LabelMouseExited

    private void PB5_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB5_LabelMouseMoved
        DVPB5.movingMouseStyle(PB5_Label, labelMovingColor);
    }//GEN-LAST:event_PB5_LabelMouseMoved

    private void PB5_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB5_LabelMouseExited
        DVPB5.exiteMouseStyle(PB5_Label);
    }//GEN-LAST:event_PB5_LabelMouseExited

    private void PB6_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB6_LabelMouseMoved
        DVPB6.movingMouseStyle(PB6_Label, labelMovingColor);
    }//GEN-LAST:event_PB6_LabelMouseMoved

    private void PB6_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB6_LabelMouseExited
        DVPB6.exiteMouseStyle(PB6_Label);
    }//GEN-LAST:event_PB6_LabelMouseExited

    private void PB7_Label5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB7_Label5MouseMoved
        DVPB7.movingMouseStyle(PB7_Label5, labelMovingColor);
    }//GEN-LAST:event_PB7_Label5MouseMoved

    private void PB7_Label5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB7_Label5MouseExited
        DVPB7.exiteMouseStyle(PB7_Label5);
    }//GEN-LAST:event_PB7_Label5MouseExited

    private void PA0_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA0_LabelMouseMoved
        DVPA0.movingMouseStyle(PA0_Label, labelMovingColor);
        // DVPA0.setIsClicked(false);
        System.out.println("Moving");
    }//GEN-LAST:event_PA0_LabelMouseMoved

    private void PA1_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA1_LabelMouseMoved
        DVPA1.movingMouseStyle(PA1_Label, labelMovingColor);
    }//GEN-LAST:event_PA1_LabelMouseMoved

    private void PA2_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA2_LabelMouseMoved
        DVPA2.movingMouseStyle(PA2_Label, labelMovingColor);
    }//GEN-LAST:event_PA2_LabelMouseMoved

    private void PA3_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA3_LabelMouseMoved
        DVPA3.movingMouseStyle(PA3_Label, labelMovingColor);

    }//GEN-LAST:event_PA3_LabelMouseMoved

    private void PA4_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA4_LabelMouseMoved
        DVPA4.movingMouseStyle(PA4_Label, labelMovingColor);
    }//GEN-LAST:event_PA4_LabelMouseMoved

    private void PA5_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA5_LabelMouseMoved
        DVPA5.movingMouseStyle(PA5_Label, labelMovingColor);
    }//GEN-LAST:event_PA5_LabelMouseMoved

    private void PA6_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA6_LabelMouseMoved
        DVPA6.movingMouseStyle(PA6_Label, labelMovingColor);
    }//GEN-LAST:event_PA6_LabelMouseMoved

    private void PA7_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA7_LabelMouseMoved
        DVPA7.movingMouseStyle(PA7_Label, labelMovingColor);
    }//GEN-LAST:event_PA7_LabelMouseMoved

    private void PA0_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA0_LabelMouseExited
        DVPA0.exiteMouseStyle(PA0_Label);
        System.out.println("exite");
    }//GEN-LAST:event_PA0_LabelMouseExited

    private void PA1_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA1_LabelMouseExited
        DVPA1.exiteMouseStyle(PA1_Label);
    }//GEN-LAST:event_PA1_LabelMouseExited

    private void PA2_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA2_LabelMouseExited
        DVPA2.exiteMouseStyle(PA2_Label);

    }//GEN-LAST:event_PA2_LabelMouseExited

    private void PA3_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA3_LabelMouseExited
        DVPA3.exiteMouseStyle(PA3_Label);
    }//GEN-LAST:event_PA3_LabelMouseExited

    private void PA4_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA4_LabelMouseExited
        DVPA4.exiteMouseStyle(PA4_Label);
    }//GEN-LAST:event_PA4_LabelMouseExited

    private void PA5_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA5_LabelMouseExited
        DVPA5.exiteMouseStyle(PA5_Label);
    }//GEN-LAST:event_PA5_LabelMouseExited

    private void PA6_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA6_LabelMouseExited
        DVPA6.exiteMouseStyle(PA6_Label);
    }//GEN-LAST:event_PA6_LabelMouseExited

    private void PA7_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA7_LabelMouseExited
        DVPA7.exiteMouseStyle(PA7_Label);
    }//GEN-LAST:event_PA7_LabelMouseExited

    private void PC0_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC0_LabelMouseMoved
        DVPC0.movingMouseStyle(PC0_Label, labelMovingColor);

    }//GEN-LAST:event_PC0_LabelMouseMoved

    private void PC1_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC1_LabelMouseMoved
        DVPC1.movingMouseStyle(PC1_Label, labelMovingColor);
    }//GEN-LAST:event_PC1_LabelMouseMoved

    private void PC2_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC2_LabelMouseMoved
        DVPC2.movingMouseStyle(PC2_Label, labelMovingColor);
    }//GEN-LAST:event_PC2_LabelMouseMoved

    private void PC3_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC3_LabelMouseMoved
        DVPC3.movingMouseStyle(PC3_Label, labelMovingColor);
    }//GEN-LAST:event_PC3_LabelMouseMoved

    private void PC4_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC4_LabelMouseMoved
        DVPC4.movingMouseStyle(PC4_Label, labelMovingColor);
    }//GEN-LAST:event_PC4_LabelMouseMoved

    private void PC5_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC5_LabelMouseMoved
        DVPC5.movingMouseStyle(PC5_Label, labelMovingColor);
    }//GEN-LAST:event_PC5_LabelMouseMoved

    private void PC6_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC6_LabelMouseMoved
        DVPC6.movingMouseStyle(PC6_Label, labelMovingColor);
    }//GEN-LAST:event_PC6_LabelMouseMoved

    private void PC7_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC7_LabelMouseMoved
        DVPC7.movingMouseStyle(PC7_Label, labelMovingColor);
    }//GEN-LAST:event_PC7_LabelMouseMoved

    private void PC0_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC0_LabelMouseExited
        DVPC0.exiteMouseStyle(PC0_Label);
    }//GEN-LAST:event_PC0_LabelMouseExited

    private void PC1_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC1_LabelMouseExited
        DVPC1.exiteMouseStyle(PC1_Label);

    }//GEN-LAST:event_PC1_LabelMouseExited

    private void PC2_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC2_LabelMouseExited
        DVPC2.exiteMouseStyle(PC2_Label);
    }//GEN-LAST:event_PC2_LabelMouseExited

    private void PC3_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC3_LabelMouseExited
        DVPC3.exiteMouseStyle(PC3_Label);
    }//GEN-LAST:event_PC3_LabelMouseExited

    private void PC4_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC4_LabelMouseExited
        DVPC4.exiteMouseStyle(PC4_Label);
    }//GEN-LAST:event_PC4_LabelMouseExited

    private void PC5_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC5_LabelMouseExited
        DVPC5.exiteMouseStyle(PC5_Label);
    }//GEN-LAST:event_PC5_LabelMouseExited

    private void PC6_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC6_LabelMouseExited
        DVPC6.exiteMouseStyle(PC6_Label);
    }//GEN-LAST:event_PC6_LabelMouseExited

    private void PC7_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PC7_LabelMouseExited
        DVPC7.exiteMouseStyle(PC7_Label);
    }//GEN-LAST:event_PC7_LabelMouseExited

    private void PD0_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD0_LabelMouseMoved
        DVPD0.movingMouseStyle(PD0_Label, labelMovingColor);
    }//GEN-LAST:event_PD0_LabelMouseMoved

    private void PD1_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD1_LabelMouseMoved
        DVPD1.movingMouseStyle(PD1_Label, labelMovingColor);
    }//GEN-LAST:event_PD1_LabelMouseMoved

    private void PD2_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD2_LabelMouseMoved
        DVPD2.movingMouseStyle(PD2_Label, labelMovingColor);
    }//GEN-LAST:event_PD2_LabelMouseMoved

    private void PD3_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD3_LabelMouseMoved
        DVPD3.movingMouseStyle(PD3_Label, labelMovingColor);
    }//GEN-LAST:event_PD3_LabelMouseMoved

    private void PD4_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD4_LabelMouseMoved
        DVPD4.movingMouseStyle(PD4_Label, labelMovingColor);
    }//GEN-LAST:event_PD4_LabelMouseMoved

    private void PD5_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD5_LabelMouseMoved
        DVPD5.movingMouseStyle(PD5_Label, labelMovingColor);
    }//GEN-LAST:event_PD5_LabelMouseMoved

    private void PD6_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD6_LabelMouseMoved
        DVPD6.movingMouseStyle(PD6_Label, labelMovingColor);
    }//GEN-LAST:event_PD6_LabelMouseMoved

    private void PD7_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD7_LabelMouseMoved
        DVPD7.movingMouseStyle(PD7_Label, labelMovingColor);

    }//GEN-LAST:event_PD7_LabelMouseMoved

    private void PD0_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD0_LabelMouseExited
        DVPD0.exiteMouseStyle(PD0_Label);
    }//GEN-LAST:event_PD0_LabelMouseExited

    private void PD1_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD1_LabelMouseExited
        DVPD1.exiteMouseStyle(PD1_Label);
    }//GEN-LAST:event_PD1_LabelMouseExited

    private void PD2_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD2_LabelMouseExited
        DVPD2.exiteMouseStyle(PD2_Label);
    }//GEN-LAST:event_PD2_LabelMouseExited

    private void PD3_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD3_LabelMouseExited
        DVPD3.exiteMouseStyle(PD3_Label);
    }//GEN-LAST:event_PD3_LabelMouseExited

    private void PD4_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD4_LabelMouseExited
        DVPD4.exiteMouseStyle(PD4_Label);
    }//GEN-LAST:event_PD4_LabelMouseExited

    private void PD5_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD5_LabelMouseExited
        DVPD5.exiteMouseStyle(PD5_Label);
    }//GEN-LAST:event_PD5_LabelMouseExited

    private void PD6_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD6_LabelMouseExited
        DVPD6.exiteMouseStyle(PD6_Label);
    }//GEN-LAST:event_PD6_LabelMouseExited

    private void PD7_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PD7_LabelMouseExited
        DVPD7.exiteMouseStyle(PD7_Label);
    }//GEN-LAST:event_PD7_LabelMouseExited

    private void PA0_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA0_LabelMouseClicked

        togglePinDirection(0, PA0_Label, DVPA0.getLabelColorBeforeChange());
        System.out.println("clicked");
    }//GEN-LAST:event_PA0_LabelMouseClicked

    private void PA1_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA1_LabelMouseClicked

    }//GEN-LAST:event_PA1_LabelMouseClicked

    private void PA2_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PA2_LabelMouseClicked

    }//GEN-LAST:event_PA2_LabelMouseClicked
    private void togglePinDirection(int pinNum, JLabel PinDirectionLabel, Color labelColorBeforeChange) {
        DIO Dio = new DIO(currentFile);
        DVPA0.setIsClicked(true);
        DVPA0.setLabelColorAfterChange(Dio.togglePinValue(pinNum, PinDirectionLabel, labelColorBeforeChange));

    }

    private void getPinsDirection() {
        DIO Dio = new DIO(currentFile);
        JLabel PinDirectionLabel[] = {PA0_Label, PA1_Label, PA2_Label, PA3_Label, PA4_Label, PA5_Label, PA6_Label, PA7_Label, PB0_Label, PB1_Label, PB2_Label, PB3_Label, PB4_Label, PB5_Label, PB6_Label, PB7_Label5, PC0_Label, PC1_Label, PC2_Label, PC3_Label, PC4_Label, PC5_Label, PC6_Label, PC7_Label, PD0_Label, PD1_Label, PD2_Label, PD3_Label, PD4_Label, PD5_Label, PD6_Label, PD7_Label};
        Dio.getDriverElementsValues();
        config = Dio.setPinDirectionColor(PinDirectionLabel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentProject(currentFile, name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADCContentPanel;
    private javax.swing.JLabel ADCIconLabel;
    private javax.swing.JLabel ADCLabel;
    private javax.swing.JPanel ADCPanel;
    private javax.swing.JLabel AVRIcon;
    private javax.swing.JLabel ApplyIconLabel;
    private javax.swing.JLabel ApplyLabel;
    private javax.swing.JPanel ApplyPanel;
    private javax.swing.JPanel DIOContentPanel;
    private javax.swing.JLabel DIOIconLabel;
    private javax.swing.JLabel DIOLabel;
    private javax.swing.JPanel DIOPanel;
    private javax.swing.JLabel PA0_Label;
    private javax.swing.JLabel PA1_Label;
    private javax.swing.JLabel PA2_Label;
    private javax.swing.JLabel PA3_Label;
    private javax.swing.JLabel PA4_Label;
    private javax.swing.JLabel PA5_Label;
    private javax.swing.JLabel PA6_Label;
    private javax.swing.JLabel PA7_Label;
    private javax.swing.JLabel PB0_Label;
    private javax.swing.JLabel PB1_Label;
    private javax.swing.JLabel PB2_Label;
    private javax.swing.JLabel PB3_Label;
    private javax.swing.JLabel PB4_Label;
    private javax.swing.JLabel PB5_Label;
    private javax.swing.JLabel PB6_Label;
    private javax.swing.JLabel PB7_Label5;
    private javax.swing.JLabel PC0_Label;
    private javax.swing.JLabel PC1_Label;
    private javax.swing.JLabel PC2_Label;
    private javax.swing.JLabel PC3_Label;
    private javax.swing.JLabel PC4_Label;
    private javax.swing.JLabel PC5_Label;
    private javax.swing.JLabel PC6_Label;
    private javax.swing.JLabel PC7_Label;
    private javax.swing.JLabel PD0_Label;
    private javax.swing.JLabel PD1_Label;
    private javax.swing.JLabel PD2_Label;
    private javax.swing.JLabel PD3_Label;
    private javax.swing.JLabel PD4_Label;
    private javax.swing.JLabel PD5_Label;
    private javax.swing.JLabel PD6_Label;
    private javax.swing.JLabel PD7_Label;
    private javax.swing.JPanel USARTContentPanel;
    private javax.swing.JLabel USARTIconLabel;
    private javax.swing.JLabel USARTLabel;
    private javax.swing.JPanel USARTPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel3;
    private javax.swing.JLabel exitLabel4;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pointerADCPanel;
    private javax.swing.JPanel pointerApplyPanel;
    private javax.swing.JPanel pointerDIOPanel;
    private javax.swing.JPanel pointerUSARTPanel;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JPanel projectNamePanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
